### ISSUE TITLE
TraceWriter obsolete?

### ISSUE THREAD

**Issue by StefH** [devkimchi/Azure-Functions-V2-Dependency-Injection-Sample#1]
When upgrading the project dependencies to latests, I get a warning that `TraceWriter` is obsolete. This needs to be replaced by `ILogger`.

**Comment by justinyoo** [comment]
@StefH Thanks for the comment! Yes, you're right. This is just an example code. By the way, I'm actually offering a NuGet package for this:

* https://github.com/aliencube/AzureFunctions.Extensions
* https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.DependencyInjection/

The package supports both V1 and V2, without having to rely on 3rd party IoC container libraries. It also supports both `TraceWriter` and `ILogger` of users' choice. Therefore, in the meantime, you can use that package.

**Comment by StefH** [comment]
I'll take a look at your NuGet package. In the meantime, I'm also investigating https://github.com/BorisWilhelms/azure-function-dependency-injection

BTW : maybe useful to put the link to that NuGet/Project also in the readme from this project ?

**Comment by justinyoo** [comment]
@StefH Boris' approach is another way of DI, but I would say it's not the best practice. Actually it's rather an anti-pattern because it violates open-closed principle.

I'll update the README file with that NuGet package details.

**Comment by StefH** [comment]
Can you explain why it violates the `open-closed principle`?

**Comment by justinyoo** [comment]
https://twitter.com/justinchronicle/status/1062001034308988934
